package com.sigetel.web.wsdl.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "AuthService", targetNamespace = "http://authservices.ws.gt.tigo.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthService {


    /**
     *
     * @param password
     * @param ldapId
     * @param user
     * @return
     *     returns com.tigo.gt.ws.authservices.UserInformationResponse
     */
    @WebMethod
    @WebResult(name = "userInfo", partName = "userInfo")
    public UserInformationResponse requestUserInfo(
        @WebParam(name = "ldapId", partName = "ldapId")
        int ldapId,
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "password", partName = "password")
        String password);

}
