package com.sigetel.web.wsdl.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "AuthenticationServiceSoapBindingQSService", targetNamespace = "http://authservices.ws.gt.tigo.com/", wsdlLocation = "http://172.30.13.44:8011/DTHWeb/AuthenticationService/V1?wsdl")
public class AuthenticationServiceSoapBindingQSService
    extends Service
{

    private final static URL AUTHENTICATIONSERVICESOAPBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTHENTICATIONSERVICESOAPBINDINGQSSERVICE_EXCEPTION;
    private final static QName AUTHENTICATIONSERVICESOAPBINDINGQSSERVICE_QNAME = new QName("http://authservices.ws.gt.tigo.com/", "AuthenticationServiceSoapBindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.30.13.44:8011/DTHWeb/AuthenticationService/V1?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHENTICATIONSERVICESOAPBINDINGQSSERVICE_WSDL_LOCATION = url;
        AUTHENTICATIONSERVICESOAPBINDINGQSSERVICE_EXCEPTION = e;
    }

    public AuthenticationServiceSoapBindingQSService() {
        super(__getWsdlLocation(), AUTHENTICATIONSERVICESOAPBINDINGQSSERVICE_QNAME);
    }

    public AuthenticationServiceSoapBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHENTICATIONSERVICESOAPBINDINGQSSERVICE_QNAME, features);
    }

    public AuthenticationServiceSoapBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, AUTHENTICATIONSERVICESOAPBINDINGQSSERVICE_QNAME);
    }

    public AuthenticationServiceSoapBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHENTICATIONSERVICESOAPBINDINGQSSERVICE_QNAME, features);
    }

    public AuthenticationServiceSoapBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthenticationServiceSoapBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AuthService
     */
    @WebEndpoint(name = "AuthenticationServiceSoapBindingQSPort")
    public AuthService getAuthenticationServiceSoapBindingQSPort() {
        return super.getPort(new QName("http://authservices.ws.gt.tigo.com/", "AuthenticationServiceSoapBindingQSPort"), AuthService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthService
     */
    @WebEndpoint(name = "AuthenticationServiceSoapBindingQSPort")
    public AuthService getAuthenticationServiceSoapBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://authservices.ws.gt.tigo.com/", "AuthenticationServiceSoapBindingQSPort"), AuthService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHENTICATIONSERVICESOAPBINDINGQSSERVICE_EXCEPTION!= null) {
            throw AUTHENTICATIONSERVICESOAPBINDINGQSSERVICE_EXCEPTION;
        }
        return AUTHENTICATIONSERVICESOAPBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
